### ISSUE TITLE
support in gnome 42 required

### ISSUE THREAD

**Issue by tejasness** [cansozbir/gnome-shell-toggle-night-light-extension#10]
Is there any plan to support gnome 42?

**Comment by cansozbir** [comment]
Definitely, I'll take a look if it already works on 42, if not, I'll bring the support somehow. 
By the way, this is going to be the final release probably, since gnome plans to implement something even better with GNOME 43.
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4795

**Comment by tejasness** [comment]
Alright, thanks!

**Comment by epilif3sotnas** [comment]
At least Manjaro Unstable already has Gnome 42, but I can't upgrade because this extension isn't supported yet. :cry:

**Comment by GeraldPfeifer** [comment]
You can just edit .local/share/gnome-shell/extensions/toggle-night-light@cansozbir.github.io/metadata.json in your home directory and add a line with "42" below the one reading "41", and it'll work fine.

I created a pull request ( https://github.com/cansozbir/gnome-shell-toggle-night-light-extension/pull/11 ) for just that.

**Comment by cansozbir** [comment]
@GeraldPfeifer  I just merged it, thank you for your support. I am closing this issue.
