### ISSUE TITLE
Add support for Gnome 40

### ISSUE THREAD

**Issue by abtinmo** [cansozbir/gnome-shell-toggle-night-light-extension#2]

**Comment by cansozbir** [comment]
@abtinmo Hey, did you check the changes you made? If it works I think we can merge.

**Comment by abtinmo** [comment]
> @abtinmo Hey, did you check the changes you made? If it works I think we can merge.

hello, yeah i have tested the changes on openSUSE with gnome 40. 
and also thank you for your great work 👍🏼
