### ISSUE TITLE
Weird icon on Gnome 41.2

### ISSUE THREAD

**Issue by reisaraujo-miguel** [cansozbir/gnome-shell-toggle-night-light-extension#9]
I just installed this extension and noticed that one of the icons on the top bar appears to be cut off at the top, but I don't really know if this should be what this icon should look like or not.

![image](https://user-images.githubusercontent.com/58122451/146654182-f812e93a-8c25-4c8d-8ddb-b2001b153536.png)

**Comment by cansozbir** [comment]
There is nothing wrong with the icon, the extension is using a default icon from your system. You can realize that if you change your system's icon theme, this icon will change too.

**Comment by reisaraujo-miguel** [comment]
Ok. I thought it was in the wrong size, so it was cut off at the top, but if the icon looks like this, I think I can close this issue.
